version: "3"
services:
  container_name:
    image: image_name:tag
    container_name: container_name
    restart: unless-stopped
    volumes:
      - ./data:/path/to/data
    networks:
      - proxy

networks:
  proxy:
    external: true
