version: "3"
services:
  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --loglevel warning --requirepass redis_password
    ports:
      - "6379:6379" # Redis Port
    networks:
      - proxy

networks:
  proxy:
    external: true
