version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:1.31.0
    container_name: vaultwarden
    restart: unless-stopped
    # Uncomment the following lines to use a custom domain
    # environment:
    #   - DOMAIN=https://vaultwarden.example.com
    volumes:
      - ./data:/data
    ports:
      - "8080:80" # Web interface
    networks:
      - proxy

networks:
  proxy:
    external: true
